<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Notulensi extends Model
{
    use HasFactory;

    protected $table = 'notulensis';

    protected $fillable = [
        'agenda_id',
        'audio_path',
        'audio_name',
        'audio_files',
        'transkrip_raw',
        'ringkasan',
        'pembahasan',
        'keputusan',
        'kesimpulan',
        'status',
        'catatan_revisi',
        'approver_id',
        'last_edited_by_id',
        'pembahasan_title',
        'keputusan_title',
        'is_transcribing',
        'transkrip_error',
    ];

    protected $casts = [
        'audio_files' => 'array',
        'is_transcribing' => 'boolean',
    ];

    public function agenda(): BelongsTo
    {
        return $this->belongsTo(Agenda::class, 'agenda_id');
    }

    public function approver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approver_id');
    }

    public function lastEditedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'last_edited_by_id');
    }

    public function getPembahasanTitleAttribute($value)
    {
        return $value ?: 'Poin Pembahasan Rapat';
    }

    public function getKeputusanTitleAttribute($value)
    {
        return $value ?: 'Daftar Keputusan Rapat';
    }

    public function getRingkasanHtmlAttribute()
    {
        return self::markdownToHtml($this->ringkasan);
    }

    public static function markdownToHtml($text)
    {
        if (empty($text)) {
            return '';
        }

        // Clean any codeblock fence markers (```markdown or ```) generated by AI
        $text = preg_replace('/```(?:markdown)?/i', '', $text);
        
        // Remove redundant dash/asterisk before numbers (e.g. "- 1. Topic" -> "1. Topic")
        $text = preg_replace('/^\s*[\-\*]\s*(\d+[\.\)])/m', '$1', $text);
        
        $text = trim($text);

        $html = htmlspecialchars($text, ENT_QUOTES, 'UTF-8');

        // Headers
        $html = preg_replace('/^#\s+(.+)$/m', '<h3 style="font-size: 16px; font-weight: 800; color: #2e2552; margin-top: 14px; margin-bottom: 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;">$1</h3>', $html);
        $html = preg_replace('/^##\s+(.+)$/m', '<h4 style="font-size: 14px; font-weight: 700; color: #334155; margin-top: 12px; margin-bottom: 6px;">$1</h4>', $html);
        $html = preg_replace('/^###\s+(.+)$/m', '<h5 style="font-size: 13px; font-weight: 700; color: #475569; margin-top: 10px; margin-bottom: 4px;">$1</h5>', $html);

        // Bold
        $html = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $html);

        // Italic
        $html = preg_replace('/\*([^\*]+)\*/', '<em>$1</em>', $html);

        // Sub-fields like "- Isi:" or "Isi:" or "- Penjelasan:" -> Indented sub-block
        $html = preg_replace('/^\s*(?:[\-\*]\s*)?(Isi|Penjelasan|Catatan|Keputusan|Hasil|Tugas|Waktu):\s*(.+)$/m', '<div style="margin-left: 20px; font-size: 13px; color: #475569; margin-top: 2px; margin-bottom: 4px;"><strong style="color: #1e293b;">$1:</strong> $2</div>', $html);

        // Numbered list items (e.g. "1. Judul Poin") -> Bold title with top margin
        $html = preg_replace('/^\s*(\d+[\.\)])\s+(.+)$/m', '<div style="font-weight: 700; color: #1e293b; font-size: 13.5px; margin-top: 8px; margin-bottom: 2px;">$1 $2</div>', $html);

        // Regular bullet items (e.g. "- Poin biasa")
        $html = preg_replace('/^\s*[\-\*]\s+(.+)$/m', '<div style="margin-left: 12px; font-size: 13px; color: #334155; margin-bottom: 3px;">• $1</div>', $html);

        // Convert line breaks
        $html = nl2br($html);

        // Clean up excessive <br /> around <div> and <h*> elements
        $html = preg_replace('/(<\/(?:div|h[345])>)\s*(<br\s*\/?>\s*)+/i', '$1', $html);
        $html = preg_replace('/(<br\s*\/?>\s*)+(<(?:div|h[345])[\s>])/i', '$2', $html);

        return $html;
    }
}
